#!/bin/bash

# Environments related with the renderfarm dispatcher.
# currently these environments are very much
# deadline centric. However, these names may
# change when we introduce a new renderfarm manager.
export DISPATCHER_RENDERFARM_PRIORITY="50"
export DISPATCHER_RENDERFARM_SPLITSIZE="5"
export DISPATCHER_RENDERFARM_GROUP="farm"
export DISPATCHER_RENDERFARM_POOL=""
export DISPATCHER_RENDERFARM_SECONDARYPOOL=""

# application defaults. The default for the applications is defined by
# the convention DISPATCHER_RENDERFARM_<APPLICATION>_<OPTION>.

# maya defaults
export DISPATCHER_RENDERFARM_MAYA_GROUP="$DISPATCHER_RENDERFARM_GROUP"
export DISPATCHER_RENDERFARM_MAYA_POOL="cg"

# nuke defaults
export DISPATCHER_RENDERFARM_NUKE_GROUP="$DISPATCHER_RENDERFARM_GROUP"
export DISPATCHER_RENDERFARM_NUKE_POOL="comp"
