#!/bin/bash

# directory used to tell the location for temporary files that are
# shared across the network
export INGESTOR_TEMP_REMOTE_DIR="$UPIPE_ROOT/temp"

# user used for publishing versions (optional) in the ingestor
#export INGESTOR_VERSION_PUBLISHER_USER="upub"

# Environments related with the renderfarm dispatcher.
# currently these environments are very much
# deadline centric. However, these names may
# change when we introduce a new renderfarm manager.
export INGESTOR_DISPATCHER_RENDERFARM_PRIORITY="50"
export INGESTOR_DISPATCHER_RENDERFARM_SPLITSIZE="5"
export INGESTOR_DISPATCHER_RENDERFARM_GROUP="farm"
export INGESTOR_DISPATCHER_RENDERFARM_POOL=""
export INGESTOR_DISPATCHER_RENDERFARM_SECONDARYPOOL=""

# application defaults. The default for the applications is defined by
# the convention INGESTOR_DISPATCHER_RENDERFARM_<APPLICATION>_<OPTION>.

# maya defaults
export INGESTOR_DISPATCHER_RENDERFARM_MAYA_GROUP="$INGESTOR_DISPATCHER_RENDERFARM_GROUP"
export INGESTOR_DISPATCHER_RENDERFARM_MAYA_POOL="cg"

# nuke defaults
export INGESTOR_DISPATCHER_RENDERFARM_NUKE_GROUP="$INGESTOR_DISPATCHER_RENDERFARM_GROUP"
export INGESTOR_DISPATCHER_RENDERFARM_NUKE_POOL="comp"
