#!/bin/bash

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# shotgun address
#export SHOTGUN_URL="https://..."

# session configuration used by ushotgun
export USHOTGUN_SESSION_CONFIG_PATH="$dir/data/ushotgunSession"
